package seba0.javaszc4.malafirma.kadry.view;

enum ViewType {
    LISTA_PRACOWNICY,
    LISTA_STANOWISKA,
    LISTA_DZIALY,
    DODAJ_PRACOWNIKA,
    DODAJ_STANOWISKO,
    DODAJ_DZIAL,
    USUN_PRACOWNIKA,
    USUN_STANOWISKO,
    USUN_DZIAL,
    ZAKONCZ
}
